#   --------------------
#     GENERAL OPTIONS
#   --------------------

[LatticeFiles]

# Main path where the sequence and beam params are
main_input_path = "inputs/lattices/higgs/"
sequence_path = "fccee_h.madx"          # Name of the file with the seq
params_path = "h_parameter_table.txt"   # Name of the file with the beam's params

# Name of the sequence
sequence_name = false			# Name of the sequence. If set to false, take the first sequence available

# Measuring elements keywords
measure_class = ["Marker"]
optics_class = ["Quadrupole"]

# What parameters use for the twiss
measure_parameters = ["name", "s", "betx", "bety", "mux", "muy"]
optics_parameters = ["name", "s", "betx", "bety", "mux", "muy", "alfx", "alfy"]

# Debug flag 
debug = true       # If true, MADX will log to console 


[BeamParameters]
# Parameters for the beam to simulate. 
# Telling the mass, charge and direction of the beam is mandatory, as these parameters don't usually appear on the parameter's table
# Set false to choose the param on the table

energy = 120.0      		# Energy of the beam [GeV]
charge = -1         		# Charge of the particle [in units of e]
mass = 0.511        		# Mass of the particle [MeV/c^2]
direction = -1       		# Direction (1 for left to right, -1 the other way around)
radiate = false     		# Simulate syncrotron radiation



# These options are usually set on the parameter's table
# TODO: add these if they're even needed
current = false         	# [Amps]
emittance_x = false     	# [m*rad]
emittance_y = false     	# [m*rad]


[TrackParameters]
# Parameters for the tracking simulation, such as injection parameters, number of turns and methods

# Random initial positions (to change the phase)
random_positions = true
random_velocities = true

# Random sigmas to create the initial injection conditions
x_sigma = 0.000010
y_sigma = 0.000001
px_sigma = 0.000010
py_sigma = 0.000010

# Manual insertions 
x = 0.00001345 
y = 0.0000006 
px = 0.0
py = 0.0

# Other parameters
N = 256             	# Number of turns  
context = "CPU"		# Runtime context: CPU [1 thread, usually fastest], CPUN [to use N threads], CUPY, OPENCL


#   -----------------------------
#    SYSTEM'S INPUTS AND OUTPUTS
#   -----------------------------


[NominalSystem]

# Which twiss files to create for the nominal lattice
measure_twiss = true            # Twiss of the BPMs (or other measuring elements)
optics_twiss = true             # Twiss of the optics (quadrupoles)


# IMPORTANT: these nominal files will be used throughout the code, cannot be changed. 
# For the program to work, all of them have to exist
main_output_path = "outputs/nominal"
measure_path = "nominal_measurements_twiss"		# Note: will be saved in packet format to read faster, 
optics_path = "nominal_quads_twiss"			# if needed in .tfs, then activate save_tfs option
integrals_path = "nominal_optics_integrals"		 

save_tfs = true						# Select wether we'll save the .tfs file


[ErrorsSystem]

# Which twiss files to create for the nominal lattice
measure_twiss = true            # Twiss of the BPMs (or other measuring elements)
optics_twiss = true             # Twiss of the optics (quadrupoles)
TBT_track = true                # Wether or not to track

# Input options (where the erros/corrections will be)
modifications_path = "inputs/IR_errors.madx"

# Output options
main_output_path = "outputs/errors"
measure_path = "E_measurements_twiss"
optics_path = "E_quads_twiss"
track_path = "E_track"
APJ_path = "APJ/"

save_tfs = true					# Select wether we'll save the .tfs file

# Plot options
plot_APJ = true

# Reference BPM and arcs for APJ calculation
ref_bpm = "BPM_QD0AL.0"
left_arc = [15000, 20000]
right_arc = [23500, 30000]
avermax_TH = 0.5               # Avermax \Psi treshold (in units of pi)

[CorrectionsSystem]

# Which twiss files to create for the nominal lattice
measure_twiss = true            # Twiss of the BPMs (or other measuring elements)
optics_twiss = true             # Twiss of the optics (quadrupoles)
TBT_track = true                # Wether or not to track

# Input options
modifications_path = "inputs/IR_errors+corrections.madx"

# Output options
main_output_path = "outputs/corrections/"
measure_path = "C_measurements_twiss.tfs"
optics_path = "C_quads_twiss.tfs"
track_path = "C_track"
APJ_path = "APJ/"

save_tfs = true					# Select wether we'll save the .tfs file

# Plot options
plot_APJ = false

# Reference BPM and arcs for APJ calculation
ref_bpm = "BPM_QD0AL.0"
left_arc = [15000, 20000]
right_arc = [23500, 30000]
avermax_TH = 0.5               # Avermax \Psi treshold (in units of pi)

